FROM timescale/timescaledb:0.10.1-pg10
COPY deploy/metricsdb/initdb/* /docker-entrypoint-initdb.d/
COPY deploy/metricsdb/nuvo-entrypoint.sh /
COPY deploy/metricsdb/pg_hba.conf /etc/nuvoloso/
RUN chmod +x /nuvo-entrypoint.sh /docker-entrypoint-initdb.d/*.sh
ENTRYPOINT ["/nuvo-entrypoint.sh"]
CMD ["postgres"]
